set1 = {6,7,8,9,10,11,12}
A= set()
print(A)
print(A.add(1))
print(A.add(2))
print(A.add(4))
print(A.add(3))
print(A.add(5))
print(A.add(6))
# print(A.pop())
# print(A.remove(2))
print(A)
print(set1)
print(set1.union(A))
print(set1.intersection(A))
print(A.pop())
print(A.remove(3))
print(A.discard(2))
print(A)
